include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.i18n.dart"
    - "**/firebase_options.dart"
  errors:
    invalid_annotation_target: ignore # https://github.com/rrousselGit/freezed/issues/488#issuecomment-894358980
    depend_on_referenced_packages: ignore # зависимости слоев подключаются через pubspec_override.yaml

linter:
  rules:
    - use_super_parameters
