workspace:
  project:
    name: todo_app

global_pubspec:
  environment:
    sdk: ">=2.17.6 <3.0.0"

index_file:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"

scripts:
  pub:get: "pansy run flutter pub get"
  pub:major: 'pansy run "flutter pub upgrade --major-versions"'

  bootstrap: "pansy bootstrap && pansy script pub:get"
  generate: 'pansy bootstrap && pansy run --depend_on_packages build_runner "dart run build_runner build --delete-conflicting-outputs" && pansy bootstrap'

  clean: "pansy run --depend_on_packages flutter flutter clean && pansy run rm pubspec.lock"
