name: todo_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dino:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino

  provider: ^6.0.3
  logging: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  uuid: ^3.0.6
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  fpdart: ^0.2.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.3.6
  flutter_svg: ^1.1.1+1
  collection: ^1.16.0
  firebase_crashlytics: ^2.8.3
  firebase_core: 1.18.0
  firebase_remote_config: ^2.0.10
  flutter_keyboard_visibility: ^5.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

  index_generator: ^3.3.0
  dino_generator:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino_generator

  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3
  i18n: ^3.4.1
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/svg/icons/

index_generator:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/modules/task/domain
    - path: lib/modules/task/infrastructure
    - path: lib/modules/task/presentation
