name: todo_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dino:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino

  provider: ^6.0.3
  logging: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  uuid: ^3.0.6
  auto_route: ^4.2.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  fpdart: ^0.2.0
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

  index_generator: ^3.3.0
  dino_generator:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino_generator

  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  auto_route_generator: ^4.2.0
  retrofit_generator: ^4.0.3
  i18n: ^3.4.1

flutter:
  uses-material-design: true

index_generator:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/modules/task/domain
    - path: lib/modules/task/infrastructure
    - path: lib/modules/task/presentation
