name: todo_app
version: 1.0.4+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  dino_generator:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino_generator

flutter:
  uses-material-design: true
