name: core_infrastructure
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dino:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino

  retrofit: ^3.0.1+1
  dio: ^4.0.6
  hive_flutter: ^1.1.0
  firebase_crashlytics: ^2.8.3
  firebase_core: ^1.21.0
  firebase_remote_config: ^2.0.10
  firebase_analytics: ^9.3.2
  connectivity_plus: ^2.3.6

dev_dependencies:
  build_runner: ^2.2.0

  dino_generator:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino_generator

  retrofit_generator: ^4.0.3
  hive_generator: ^1.1.3
