name: core_presentation
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  dino:
    git:
      url: https://github.com/Exeteres/dino
      path: packages/dino

  i18n: ^3.4.1

  provider: ^6.0.3
  flutter_bloc: ^8.0.1

  flutter_svg: ^1.1.1+1
  flutter_keyboard_visibility: ^5.3.0

  sliver_tools: ^0.2.7
  diffutil_sliverlist: ^0.5.1

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

flutter:
  assets:
    - assets/icons/
