name: android_release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Check code format
        run: find . -name "*.dart" ! -name "firebase_options.dart" ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.i18n.dart" | tr '\n' ' ' | xargs flutter format --set-exit-if-changed

      - name: Statically analyze
        run: flutter analyze .

      # - name: Passing tests
      #   run: flutter test

      - name: Building APK
        working-directory: ./todo_app
        run: flutter build apk --release --bundle-sksl-path android.sksl.json

      - name: Publishing release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "todo_app/build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
