name: coverage

on:
  push:
    branches:
      - "developer"

jobs:
  build:
    name: Upload coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get dependencies in workspace directory
        run: flutter pub get

      - name: Get dependencies in other packages directory
        run: flutter pub run melos run pub:get

      - name: Check code format
        run: find . -name "*.dart" ! -name "firebase_options.dart" ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.i18n.dart" | tr '\n' ' ' | xargs flutter format --set-exit-if-changed

      - name: Statically analyze
        run: flutter analyze .

      # - name: Run tests
      #   run: flutter test --coverage

      # - name: Install lcov
      #   run: sudo apt-get install -y lcov

      # - name: Remove generated files from code coverage report
      #   run: lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' -o coverage/lcov.info

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.2.1
      #   with:
      #     file: coverage/lcov.info
      #     token: "${{ secrets.CODECOV_TOKEN }}"
