name: test

on:
  - push

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Check code format
        run: find . -name "*.dart" ! -name "firebase_options.dart" ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.i18n.dart" | tr '\n' ' ' | xargs flutter format --set-exit-if-changed

      - name: Statically analyze
        run: flutter analyze .

      # - name: Run tests
      #   run: flutter test
